name: features_tour
description: Features Tour is a package that enables you to easily create tours to introduce your widget features in your app with order.
version: 0.6.0
homepage: https://github.com/lamnhan066/features_tour

screenshots:
  - description: "Introduction"
    path: assets/intro.webp
topics:
  - features
  - discovery
  - introduction
  - guide
  - onboarding

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0